language: node_js

cache:
  directories:
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

env:
  - ELECTRON_CACHE=$HOME/.cache/electron ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

jobs:
  include:
#    - stage: Run Tests
#      os: osx
#      osx_image: xcode10.2
#      node_js: "8"
#      script:
#        - npm i &> /dev/null
#        - npm run test-node || travis_terminate 1
    - stage: Release
      os: osx
      osx_image: xcode10.2
      node_js: "8"
      if: (branch = testing/build) OR (branch = master)
      script:
        - npm run release:mac
    - stage: Build
      os: osx
      osx_image: xcode10.2
      node_js: "8"
      if: branch = staging
      script:
        - git lfs pull
        - npm run electron:mac

#    - stage: Run Tests
#      os: linux
#      node_js: "10"
#      script:
#        - nvm install 10
#        - nvm use 10
#        - git lfs pull
#        - npm i &> /dev/null
#        - npm run test-node || travis_terminate 1
    - stage: Release
      os: linux
      node_js: "10"
      if: (branch = testing/build) OR (branch = master)
      script:
        - npm run release:linux
    - stage: Build
      os: linux
      node_js: "10"
      if: branch = staging
      script:
        - npm run electron:linux

branches:
  only:
    - staging
    - master
    - testing/build
