#osx_image: xcode8.3
#
#dist: trusty
#sudo: false
#
#language: node_js
#node_js: "8"
#
#env:
#  global:
#    - ELECTRON_CACHE=$HOME/.cache/electron
#    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
#
#os:
#  - linux
#  - osx
#
#cache:
#  directories:
#    - node_modules
#    - $HOME/.cache/electron
#    - $HOME/.cache/electron-builder
#    - $HOME/.npm/_prebuilds
#
#before_install:
#  - wget -nc https://dl.winehq.org/wine-builds/Release.key
#  - sudo apt-key add Release.key
#  - sudo apt-add-repository https://dl.winehq.org/wine-builds/ubuntu/
#  - sudo apt-get update
#  - sudo apt-get install --install-recommends winehq-stable
#
#script:
#  - echo $SIGNING64 | base64 --decode > ~/codesign.pfx
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run release; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run release:mac; fi
#
#before_cache:
#  - rm -rf $HOME/.cache/electron-builder/wine


matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      language: node_js
      node_js: "10"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

    - os: linux
      services: docker
      language: generic

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

before_install:
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v2.3.1/git-lfs-$([ "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-2.3.1.tar.gz | tar -xz -C /tmp/git-lfs --strip-components 1
      export PATH="/tmp/git-lfs:$PATH"
    fi
before_script:
  - git lfs pull

script:
  - echo $SIGNING64 | base64 --decode > ~/codesign.pfx
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      docker run --rm \
        --env-file <(env | grep -vE '\r|\n' | grep -iE 'DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS|APPVEYOR_|CSC_|_TOKEN|_KEY|AWS_|STRIP|BUILD_') \
        -v ${PWD}:/project \
        -v ~/.cache/electron:/root/.cache/electron \
        -v ~/.cache/electron-builder:/root/.cache/electron-builder \
        electronuserland/builder:wine \
        /bin/bash -c "npm i && npm run release"
    else
      npm run release:mac
    fi
before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine
