language: node_js
node_js:
  - 8
sudo: required
addons:
    chrome: stable
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm set progress=false
  - npm install
script:
  - wget -O codesign.pfx "https://drive.google.com/uc?export=download&id=1YbdSa1Qa14yYgUhotVW92G21nGoSW0hV"
  - npm run release
