osx_image: xcode8.3

dist: trusty
sudo: false

language: node_js
node_js: "8"

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

os:
  - linux
  - osx

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.npm/_prebuilds

script:
  - echo $SIGNING64 | base64 --decode > ~/codesign.pfx
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run release; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run release:mac; fi

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine
