image: Visual Studio 2017

branches:
  only:
    - master
    - staging
    - testing/build

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 10 x64
  - npm i

build_script:
  - echo %APPVEYOR_REPO_BRANCH%
#  - npm run test-node
  - IF "%APPVEYOR_REPO_BRANCH%" == "staging" (echo staging) ELSE (echo release)
  - IF "%APPVEYOR_REPO_BRANCH%" == "staging" (npm run electron:windows) ELSE (npm run release:windows)

test: off
