/**
 * Synchronous IPC channels - request/response pattern via ipcMain.handle
 */
export enum SYNC_CHANNELS {
  GetFileChanges = 'getFileChanges',
  GetLocalBranches = 'getLocalBranches',
  GetRemoteBranches = 'getRemoteBranches',
  GetSubmodules = 'getSubmodules',
  GetWorktrees = 'getWorktrees',
  GetStashes = 'getStashes',
  MergeBranch = 'mergeBranch',
  RebaseBranch = 'rebaseBranch',
  ChangeHunk = 'changeHunk',
  OpenDevTools = 'openDevTools',
  GetConfigItems = 'getConfigItems',
  SetConfigItem = 'setConfigItem',
  GetFileDiff = 'getFileDiff',
  GetDiffStats = 'getDiffStats',
  GetBranchPremerge = 'getBranchPremerge',
  LoadSettings = 'loadSettings',
  SaveSettings = 'saveSettings',
  LoadRepo = 'loadRepo',
  CherryPickCommit = 'cherryPickCommit',
  RevertCommit = 'revertCommit',
  ResetToCommit = 'resetToCommit',
  OpenFolder = 'openFolder',
  SettingsChanged = 'settingsChanged',
  OpenUrl = 'openUrl',
  GitStage = 'gitStage',
  GitUnstage = 'gitUnstage',
  OpenTerminal = 'openTerminal',
  Commit = 'commit',
  GetCommitHistory = 'getCommitHistory',
  Checkout = 'checkout',
  GetDeletedStashes = 'getDeletedStashes',
  RestoreDeletedStash = 'restoreDeletedStash',
  UndoFileChanges = 'discardFileChanges',
  UndoSubmoduleChanges = 'discardSubmoduleChanges',
  Push = 'push',
  Pull = 'pull',
  Merge = 'merge',
  DeleteFiles = 'deleteFiles',
  HardReset = 'hardReset',
  DeleteBranch = 'deleteBranch',
  FastForwardBranch = 'fastForwardBranch',
  Log = 'log',
  GetVersion = 'getVersion',
  CheckForUpdates = 'checkForUpdates',
  DeleteWorktree = 'deleteWorktree',
  Minimize = 'minimize',
  Restore = 'restoreWindow',
  CloseWindow = 'closeWindow',
  CommitDiff = 'commitDiff',
  StashDiff = 'stashDiff',
  Stash = 'stash',
  SetGitSettings = 'setBulkGitSettings',
  ApplyStash = 'applyStash',
  DeleteStash = 'deleteStash',
  RenameBranch = 'renameBranch',
  CheckGitBashVersions = 'checkGitBashVersions',
  CreateBranch = 'createBranch',
  UpdateSubmodules = 'updateSubmodules',
  AddSubmodule = 'addSubmodules',
  Fetch = 'fetch',
  GetCommandHistory = 'getCommandHistory',
  CommandHistoryChanged = 'commandHistoryChanged',
  IsUpdateDownloaded = 'isUpdateDownloaded',
  RestartAndInstallUpdate = 'restartAndInstallUpdate',
  ResolveConflictUsing = 'resolveConflictUsing',
  OpenFileDialog = 'openFileDialog',
  ChangeActiveOperation = 'changeActiveOperation',
  WindowFocused = 'windowFocused',
}

/**
 * Asynchronous IPC channels - streaming operations with init/progress/complete
 */
export enum ASYNC_CHANNELS {
  Clone = 'clone',
  AddWorktree = 'addWorktree',
}

/**
 * @deprecated Use SYNC_CHANNELS and ASYNC_CHANNELS enums instead.
 * Backward-compatible alias mapping old constant names to enum values.
 */
export const Channels = {
  GETFILECHANGES: SYNC_CHANNELS.GetFileChanges,
  GETLOCALBRANCHES: SYNC_CHANNELS.GetLocalBranches,
  GETREMOTEBRANCHES: SYNC_CHANNELS.GetRemoteBranches,
  GETSUBMODULES: SYNC_CHANNELS.GetSubmodules,
  GETWORKTREES: SYNC_CHANNELS.GetWorktrees,
  GETSTASHES: SYNC_CHANNELS.GetStashes,
  MERGEBRANCH: SYNC_CHANNELS.MergeBranch,
  REBASEBRANCH: SYNC_CHANNELS.RebaseBranch,
  CHANGEHUNK: SYNC_CHANNELS.ChangeHunk,
  OPENDEVTOOLS: SYNC_CHANNELS.OpenDevTools,
  GETCONFIGITEMS: SYNC_CHANNELS.GetConfigItems,
  SETCONFIGITEM: SYNC_CHANNELS.SetConfigItem,
  GETFILEDIFF: SYNC_CHANNELS.GetFileDiff,
  GETDIFFSTATS: SYNC_CHANNELS.GetDiffStats,
  GETBRANCHPREMERGE: SYNC_CHANNELS.GetBranchPremerge,
  LOADSETTINGS: SYNC_CHANNELS.LoadSettings,
  SAVESETTINGS: SYNC_CHANNELS.SaveSettings,
  LOADREPO: SYNC_CHANNELS.LoadRepo,
  CHERRYPICKCOMMIT: SYNC_CHANNELS.CherryPickCommit,
  REVERTCOMMIT: SYNC_CHANNELS.RevertCommit,
  RESETTOCOMMIT: SYNC_CHANNELS.ResetToCommit,
  OPENFOLDER: SYNC_CHANNELS.OpenFolder,
  SETTINGSCHANGED: SYNC_CHANNELS.SettingsChanged,
  OPENURL: SYNC_CHANNELS.OpenUrl,
  GITSTAGE: SYNC_CHANNELS.GitStage,
  GITUNSTAGE: SYNC_CHANNELS.GitUnstage,
  OPENTERMINAL: SYNC_CHANNELS.OpenTerminal,
  COMMIT: SYNC_CHANNELS.Commit,
  GETCOMMITHISTORY: SYNC_CHANNELS.GetCommitHistory,
  CHECKOUT: SYNC_CHANNELS.Checkout,
  GETDELETEDSTASHES: SYNC_CHANNELS.GetDeletedStashes,
  RESTOREDELETEDSTASH: SYNC_CHANNELS.RestoreDeletedStash,
  UNDOFILECHANGES: SYNC_CHANNELS.UndoFileChanges,
  UNDOSUBMODULECHANGES: SYNC_CHANNELS.UndoSubmoduleChanges,
  PUSH: SYNC_CHANNELS.Push,
  PULL: SYNC_CHANNELS.Pull,
  MERGE: SYNC_CHANNELS.Merge,
  DELETEFILES: SYNC_CHANNELS.DeleteFiles,
  HARDRESET: SYNC_CHANNELS.HardReset,
  DELETEBRANCH: SYNC_CHANNELS.DeleteBranch,
  FASTFORWARDBRANCH: SYNC_CHANNELS.FastForwardBranch,
  LOG: SYNC_CHANNELS.Log,
  GETVERSION: SYNC_CHANNELS.GetVersion,
  CHECKFORUPDATES: SYNC_CHANNELS.CheckForUpdates,
  DELETEWORKTREE: SYNC_CHANNELS.DeleteWorktree,
  MINIMIZE: SYNC_CHANNELS.Minimize,
  RESTORE: SYNC_CHANNELS.Restore,
  CLOSEWINDOW: SYNC_CHANNELS.CloseWindow,
  COMMITDIFF: SYNC_CHANNELS.CommitDiff,
  STASHDIFF: SYNC_CHANNELS.StashDiff,
  STASH: SYNC_CHANNELS.Stash,
  SETGITSETTINGS: SYNC_CHANNELS.SetGitSettings,
  APPLYSTASH: SYNC_CHANNELS.ApplyStash,
  DELETESTASH: SYNC_CHANNELS.DeleteStash,
  RENAMEBRANCH: SYNC_CHANNELS.RenameBranch,
  ADDWORKTREE: ASYNC_CHANNELS.AddWorktree,
  CLONE: ASYNC_CHANNELS.Clone,
  CHECKGITBASHVERSIONS: SYNC_CHANNELS.CheckGitBashVersions,
  CREATEBRANCH: SYNC_CHANNELS.CreateBranch,
  UPDATESUBMODULES: SYNC_CHANNELS.UpdateSubmodules,
  ADDSUBMODULE: SYNC_CHANNELS.AddSubmodule,
  FETCH: SYNC_CHANNELS.Fetch,
  GETCOMMANDHISTORY: SYNC_CHANNELS.GetCommandHistory,
  COMMANDHISTORYCHANGED: SYNC_CHANNELS.CommandHistoryChanged,
  ISUPDATEDOWNLOADED: SYNC_CHANNELS.IsUpdateDownloaded,
  RESTARTANDINSTALLUPDATE: SYNC_CHANNELS.RestartAndInstallUpdate,
  RESOLVECONFLICTUSING: SYNC_CHANNELS.ResolveConflictUsing,
  OPENFILEDIALOG: SYNC_CHANNELS.OpenFileDialog,
  CHANGEACTIVEOPERATION: SYNC_CHANNELS.ChangeActiveOperation,
  WINDOWFOCUSED: SYNC_CHANNELS.WindowFocused,
} as const;
