name: Build/release

on:
  push:
    branches:
      - 'master'
      - 'testing/build'

jobs:
  release:
    runs-on: ${{ matrix.os }}
    environment: signing

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: true
#          mac_certs: ${{ secrets.certs }}
#          windows_certs: ${{ secrets.certs }}
#          linux_certs: ${{ secrets.certs }}
#          mac_certs_password: ${{ secrets.certs_password }}
#          windows_certs_password: ${{ secrets.certs_password }}
#          linux_certs_password: ${{ secrets.certs_password }}
